---
title: "ExchangeRate_ARIMA"
author: "Yufei Li"
date: "2017/6/15"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Data Description
```{r data description, warning=FALSE, message=FALSE}
library(readxl)
library(timeDate)
library(timeSeries)
library(TSA)
library(fUnitRoots)
library(forecast)

data <- read_excel("D:/Junior/GitHub/FDA_project_LYF/Data/MonthlyData.xls")

head(data)
dim(data)

plot(data,type="l")

da <- read_excel("D:/Junior/GitHub/FDA_project_LYF/Data/DailyData.xlsx")

head(da)
dim(da)

plot(da,type="l")
```

## Model Estimation
```{r Basic, warning=FALSE, message=FALSE}
origin=da$ExchangeRate
ex=origin[1:2766] # 2005-07-21 To 2016-07-21
acf(ex)
pacf(ex)

dex=diff(ex)
m1=ar(dex,method = 'mle')
m1$order

# ADF Test
adfTest(ex,lags=m1$order,type=c("c"))

# Take difference
dex2=diff(dex)
dex3=diff(dex2)
dex4=diff(dex3)
dex5=diff(dex4)
dex6=diff(dex5)
dex7=diff(dex6)
dex8=diff(dex7)
acf(dex8)
pacf(dex8)
```

```{r ARIMA model, warning=FALSE, message=FALSE}
#ARIMA
m2=arima(ex,c(6,4,12))
m2
Box.test(m2$residuals,lag=30,type = "Ljung")
pv2=1-pchisq(776.93,12)
pv2

```


